name: Terraform Azure Resource Group

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: <desired_version>
    - name: Configure Terraform environment variables
      run: |
        echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
      shell: bash
      
    - name: Initialize Terraform
      run: |
        terraform init
      shell: bash
    
    - name: Terraform Plan
      run: |
        terraform plan 
        shell: bash
        
    - name: Terraform Apply
      run: |
        terraform apply -auto-approve
        shell: bash
      
