name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    inputs:
      app-service-name:
        description: 'Azure App Service Name'
        required: true
      app-service-plan-name:
        description: 'Azure App Service Plan Name'
        required: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: latest

    - name: Deploy to Azure App Service
      run: |
        az webapp deployment source config-zip --name "${{ inputs.app-service-name }}" --resource-group "<your-resource-group>" --src "<path-to-zip-file>"
