name: Deploy to Azure App Service

on:
  workflow_dispatch:
    inputs:
      resource-group-name:
        description: 'Resource Group Name'
        required: true
      app-service-name:
        description: 'Azure App Service Name'
        required: true
      service-plan-id:
        description: 'Azure App Service Plan Name'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Terraform environment variables
      run: |
        echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV

    - name: Terraform Init
      working-directory: ./flow
      run: terraform init
      
    - name: Terraform plan
      working-directory: ./flow
      run: |
        terraform validate \
          -var="resource_group_name=${{ github.event.inputs.resource-group-name }}" \
          -var="app_service_name=${{ github.event.inputs.app-service-name }}" \
          -var="service_plan_id=${{ github.event.inputs.service-plan-id }}"
