name: Deploy to Azure App Service

on:
  workflow_dispatch:
    inputs:
      resourcegroup-name:
        description: 'Resource Group Name'
        required: true
      app-service-name:
        description: 'Azure App Service Name'
        required: true
      app-service-plan-name:
        description: 'Azure App Service Plan Name'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Terraform Init
      working-directory: ./flow
      run: terraform init

    - name: Terraform Apply
      working-directory: ./flow
      run: |
        terraform apply \
          -auto-approve \
          -var "app_service_name=${{ github.event.inputs.app-service-name }}" \
          -var "app_service_plan_name=${{ github.event.inputs.app-servi
